{% set name = "gmp" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gmplib.org/download/gmp/gmp-{{version}}.tar.bz2
  sha256: f51c99cb114deb21a60075ffb494c1a210eb9d7cb729ed042ddb7de9534451ea


build:
  number: 0
  skip: true [win]

requirements:
  build:
    - {{ compiler('c') }}


about:
  home: https://gmplib.org/
  license: LGPL
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See https://conda.pydata.org/docs/building/meta-yaml.html#license-file
  license_file: README
  summary: 'GNU MP is a library for arbitrary precision arithmetic'

  # The remaining entries in this section are optional, but recommended.
  description: |
    GNU MP is a library for arbitrary precision arithmetic, operating on signed
    integers, rational numbers, and floating point numbers.  It has a rich set of
    functions, and the functions have a regular interface.


extra:
  recipe-maintainers:
    - cav71
